[package]
name = "darkpool"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.16.0"
openzeppelin_token = "0.20.0"
openzeppelin_access = "0.20.0"

[dev-dependencies]
snforge_std = "0.56.0"

[[target.starknet-contract]]
sierra = true
casm = true
